In [1]:
import numpy as np

In [2]:
#row vector 
rowV = np.array([1,2,3])
print(rowV)
#column 
colV = np.array([[2],[4],[5]])
print(colV)

[1 2 3]
[[2]
 [4]
 [5]]


In [3]:
#Matrix representation
A = np.array([[1, 2], [3, 4], [5, 6]])

# Functions : 

In [4]:
# Tensor (higher dimentional 3d or more)
T = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [12]:
#Transpose
A = np.array([[1, 2, 3], [4, 5, 6]])
A_T = A.T

In [13]:
# Determinent
A = np.array([[1, 2], [3, 4]])
det = np.linalg.det(A)

In [14]:
# inverse
A = np.array([[1, 2], [3, 4]])
inv_A = np.linalg.inv(A)

In [15]:
# eigenvalues, eigenvectors
A = np.array([[4, 1], [2, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)

In [16]:
#Singular Value Decomposition (SVD) (np.linalg.svd): SVD is a factorization of a matrix and is widely used for dimensionality reduction, such as in Latent Semantic Analysis (LSA) or recommendation systems.
U, S, V = np.linalg.svd(A)


In [18]:
#Norms (np.linalg.norm): Norms measure the length or magnitude of vectors and are used in optimization problems. The L2 norm (Euclidean norm) is particularly important in machine learning algorithms such as linear regression.
v = np.array([3, 4])
norm_v = np.linalg.norm(v)
print(norm_v)

5.0


In [ ]:
#Solving Linear Equations (np.linalg.solve): Solving systems of linear equations is a key problem in optimization and machine learning. For a system Ax = b, you can find the solution x using:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)