In [2]:
import numpy as np;

In [19]:
#Significance difference between python and numpy in terms of Space and Time

In [15]:
import sys
# In Terms of Space
arrlist = list(range(1000000))
arrnumpy = np.arange(1000000);
print(f"size of arrlist { sys.getsizeof(arrlist)} bytes")
print(f"size of arrnumpy {arrnumpy.nbytes} bytes")

# In Terms of Time 
import time
# Calulating list time
lstartTime = time.time()
lsumlist = sum(arrlist)
lendTime = time.time()
sumlistTime = (lendTime - lstartTime) * 1000

# Calculating numpy time
nstartTime = time.time()
nsumlist = np.sum(arrnumpy)
nendTime = time.time()
sumnumpyTime = (nendTime - nstartTime) * 1000

print(f"Total time for excuting python list is {sumlistTime} milliseconds")
print(f"Total time for excuting python numpy is {sumnumpyTime} milliseconds")

size of arrlist 8000056 bytes
size of arrnumpy 8000000 bytes
Total time for excuting python list is 102.02264785766602 milliseconds
Total time for excuting python numpy is 0.0 milliseconds


# Numpy Arrays
## np.arange()

In [14]:
num = np.arange(10)
print(num);

[0 1 2 3 4 5 6 7 8 9]


In [28]:
# Propertites of Array

#Shape :
arr1 = np.array([[2,5,6],[3,7,8]],dtype=np.int32)
print(arr1)

arr2 = np.arange(2,13)
print(arr2)

print(arr2.size)
print(arr2.itemsize)

[[2 5 6]
 [3 7 8]]
[ 2  3  4  5  6  7  8  9 10 11 12]
11


In [33]:
# np zeros ones full
arzeros = np.zeros((2,5),float)
print(arzeros)

arones = np.zeros((2,3),str)
print(arones)

arfull = np.full((2,4,3),10,float)
print(arfull)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[['' '' '']
 ['' '' '']]
[[[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]]


In [57]:
# Slicing and Indinxing
# 1D
arr = np.array([3,5,6,8,10])
print(arr[3],arr[0])
print(arr[2:4])
print(arr[0:5:2])
print(arr[-1],arr[-5])
print(arr[:3] , arr[2:], arr[ : : 2])


#2D 

tdArr = np.array([ [1,3,5],
          [7,8,9] ])
print(tdArr[0,2])

print(tdArr[0:2,1:3])
print(tdArr[-1,-3])




5
[[3 5]
 [8 9]]
7


In [62]:
# Advance slicing and indexing

# Boolean indexing

arrT = np.array([1,5,7,2,9,10])
mask = arrT > 3;
selelem = arrT[mask]
print(selelem)
# print(arrT[arrT > 3])

# Fancy Slicing
ind = [0,3,1]
print(arrT[ind])

[ 5  7  9 10]
[1 2 5]


In [74]:
# Transporting and swapaxes
# 2D :
# arr2d = np.array([[1,2,3],
#                  [4,5,6]])
# arrTransp = arr2d.T;
# print(arrTransp)

# swapaxes = arr2d.swapaxes(1,0)
# print(swapaxes)

#3d : 
arr3d = np.array([ [ 
                     [1,2,3,4],
                     [5,6,7,8],
                     [9,10,11,12]
                   ],
                   [
                     [13,14,15,16],
                     [17,18,19,20],
                     [21,22,23,24]
                   ]
                 ])
print(arr3d)
afterswap = arr3d.swapaxes(0,1)
print(afterswap)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]


In [6]:
# pseudo Number Generation
rintegers = np.random.randint(1,100,size = 10)
print(rintegers)
rdistribution 

[99  6 51 26 13 76  8 87 74 71]


In [13]:
# Operations on 2D array 

# Matrix multilication 
mata = np.array([ [1,3,5],
                  [2,4,6],
                  [8,1,3]
                ])

matb = np.array([  [2,4,5],
                   [1,6,2],
                   [3,6,5]
                ])
result = np.matmul(mata,matb)
# print(result)

# Reshape 
arr = np.arange(1,10)
reshapeArray1 = arr.reshape((3,3))
# print(reshapeArray1)
reshapeArray2 = mata.reshape((1,9))
# print(reshapeArray2)

# Transport
mat1 = np.array([ [1,3,5],
                  [2,4,6]
                ])
matT = mat1.T;
# print(matT)

# Agrregate functions

print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))



45
9
1
5.0


In [49]:
# Universal functions

# Basic Arithmetic Operations

# arr = np.array([1,2,3,4,5])
# arradd = np.add(arr,2)
# print(arradd)
# arrsub = np.subtract(arr,2)
# print(arrAdd)
# arrmul = np.multiply(arr,2)
# print(arrAdd)
# arrdiv = np.divide(arr,2)
# print(arrdiv)
# arrmod = np.mod(arr,2)
# print(arrmod)

# Relational operator
ar1 = np.array([1,2,3,5])
ar2 = np.array([2,3,4,5])
eq = ar1 == ar2
# print(eq)
# similarly : !=  , > , < , >= , <=
# print(np.greater(ar1,ar2))
# print(np.less_equal(ar1,ar2))

#Trigonmetric Functions
arrTrig = np.array([0,np.pi/4,np.pi/2,np.pi])

ressin =  np.sin(arrTrig)
# print(ressin)

#Exponential operations
arr = np.array([2,4,5,1,5])
res1 = np.exp(arr)
res2 = np.log(arr)
# print(res1,res2)

# Broad Casting
res = arr+2
print(res)



[4 6 7 3 7]


In [45]:
# Array Manipulation


[0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
